name: preflight-g13
services:
  postgres:
    image: postgres:16-alpine
    platform: linux/amd64
    container_name: g13-database
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - g13-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - g13-app-network
  backend:
    depends_on:
      - postgres
    image: gusntc/preflight-backend:linux
    container_name: g13-backend
    ports:
      - ${PORT}:3000
    networks:
      - g13-app-network
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_APP_USER=${POSTGRES_APP_USER}
      - POSTGRES_APP_PASSWORD=${POSTGRES_APP_PASSWORD}
  frontend:
    depends_on:
      - backend
    image: gusntc/preflight-frontend:linux
    container_name: g13-frontend
    ports:
      - ${NGINX_PORT}:5177
    networks:
      - g13-app-network
    environment:
      - NGINX_PROXY=${NGINX_PROXY}
      - NGINX_PORT=${NGINX_PORT}
volumes:
  g13-data:
networks:
  g13-app-network: